title: Evergreen
description: A debug tool for Android TV devices
url: 'https://google.github.io/evergreen-checker'
theme: null
theme_color: '#9cc269'
include:
  - '*.txt'
  - .well-known
exclude:
  - '*.sh'
  - '*.yml'
  - CNAME
  - Gemfile*
  - README.md
  - vendor
github:
  - metadata
repository: google/evergreen-checker
