title: Evergreen
description: A debug tool for Android TV devices
url: 'https://chimbori.github.io/evergreen'
repository: chimbori/evergreen
theme_color: '#9cc269'

theme: null
include:
  - '*.txt'
  - .well-known
exclude:
  - '*.sh'
  - '*.yml'
  - README.md
github:
  - metadata
